services:
  mysql:
    image: 'mysql:8.0.36'
    environment:
      - 'MYSQL_DATABASE=inpeak-db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '13306:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  redis:
    image: 'redis:7.2'
    ports:
      - '6379:6379'